### ISSUE TITLE
training or eval question

### ISSUE THREAD

**Issue by devicerxx** [cvlab-columbia/SelfSupDefense#2]
Hi. Thank you for sharing the code! I think I have trouble training or evaluating. Runing the code provided, it stayed here for several hours, even I change the small contrastive batch size.
`clean contrastive=6.242605 	 adv contrastive=6.484784`
`contrastive bs 64`

**Comment by ChengzhiCU** [comment]
What GPUs do you use?  The code is evaluated on 8 2080Ti GPUs. The training part uses less GPU as we only train two layers to readout for contrastive loss. The testing needs to backward through the backbone model and consumes more memory.

**Comment by devicerxx** [comment]
Thanks! I only have two 1080Ti GPUs to use. I’m not sure it is enough. Could you please offer me any suggestions about this problem?

**Comment by ChengzhiCU** [comment]
Sure! You can use 2 positive views instead of 4, https://github.com/cvlab-columbia/SelfSupDefense/blob/d8ff606a0b115159bdbc0a19c390524e4208657d/cifar10_defense.py#L163.

And reduce the batchsize further, but this will hurt the performance if you have small batchsize for contrastive loss.

**Comment by devicerxx** [comment]
Thanks a lot!  It worked!

**Comment by ChengzhiCU** [comment]
Glad to know!
